create table BRANDS (
    ID int not null,
    NAME varchar(32) not null
);

INSERT INTO BRANDS VALUES(1, 'ZARA');
INSERT INTO BRANDS VALUES(2, 'BERSHKA');
INSERT INTO BRANDS VALUES(3, 'PULL & BEAR');


CREATE TABLE PRODUCTS (
    ID int not null,
    NAME varchar(64) not null
);

INSERT INTO PRODUCTS VALUES(35455, 'CAMISETA TEXTO COMBINADO');
INSERT INTO PRODUCTS VALUES(555, 'JEANS BÁSICO SLIM FIT');


CREATE TABLE CURRENCIES (
   ID int not null,
   NAME varchar(32) not null
);

INSERT INTO CURRENCIES VALUES(1, 'EUR');
INSERT INTO CURRENCIES VALUES(2, 'USD');
