CREATE TABLE PRICES (
  PRICE_LIST INT NOT NULL,
  BRAND_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE double NOT NULL,
  CURR_ID INT NOT NULL
);

INSERT INTO PRICES(PRICE_LIST, BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY, PRICE, CURR_ID)
VALUES (1, 1, 35455, '2020-06-14T00:00:00', '2020-12-31T23:59:59', 0, 35.50, 1);